import { chromium, devices } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const url = process.argv[2]; const SP = '.';
const b = await chromium.launch(); const c = await b.newContext({ ...devices['iPhone 13'] });
await c.addInitScript(() => localStorage.setItem('roelit:installDismissed', 'true'));
const p = await c.newPage(); const errs = [];
p.on('pageerror', (e) => errs.push(String(e))); p.on('console', (m) => m.type() === 'error' && errs.push(m.text()));
await p.goto(url); await p.waitForSelector('.deck-tile');
const crew = p.locator('.deck-tile', { hasText: 'SPORRENCESON' });
console.log('tile before:', JSON.stringify(await crew.textContent()), '| any crew name in page HTML?', /Chris Martin|Perera/.test(await p.content()));
await crew.scrollIntoViewIfNeeded(); await crew.tap(); await p.waitForTimeout(700);
await p.screenshot({ path: `${SP}/shots/50-passcode.png` });
const keys = async (code) => { for (const d of code) { await p.locator('.sheet-root.open .key', { hasText: new RegExp('^' + d + '$') }).tap(); await p.waitForTimeout(60); } };
await keys('111111'); await p.waitForTimeout(300);
await p.screenshot({ path: `${SP}/shots/51-wrong.png` });
await p.waitForTimeout(1500);
console.log('after wrong code -> keypad still open:', !!(await p.$('.sheet-root.open .keypad')), '| deck sheet open:', !!(await p.$('.sheet-root.open .deck-hero')));
await keys(process.env.CREW_CODE); await p.waitForTimeout(2500);
console.log('after right code -> deck sheet open:', !!(await p.$('.sheet-root.open .deck-hero')));
await p.screenshot({ path: `${SP}/shots/52-unlocked.png` });
await p.locator('.sheet-root.open .btn-primary').tap(); await p.waitForTimeout(500);
await p.setViewportSize({ width: 844, height: 390 }); await p.waitForTimeout(300);
if (await p.$('text=Allow microphone')) { await p.locator('text=Allow microphone').tap(); await p.waitForTimeout(300); }
await p.locator('.pre-actions .btn-primary').tap(); await p.waitForTimeout(3600);
console.log('round word:', (await p.locator('.word').textContent())?.replace(/\n/g, ' '));
await p.screenshot({ path: `${SP}/shots/53-crew-round.png` });
await p.keyboard.press('Escape'); await p.waitForTimeout(300);
await p.setViewportSize({ width: 390, height: 844 }); await p.reload(); await p.waitForSelector('.deck-tile'); await p.waitForTimeout(2500);
await p.locator('.tabbar button').nth(1).tap(); await p.waitForTimeout(300);
console.log('decks row after reload:', await p.locator('.row', { hasText: 'SPORRENCESON' }).textContent());
await p.locator('.row', { hasText: 'SPORRENCESON' }).tap(); await p.waitForTimeout(700);
console.log('preview opens without code (remembered):', !!(await p.$('.sheet-root.open .card-list')));
await p.locator('text=Lock again').tap(); await p.waitForTimeout(800);
console.log('after Lock again -> row:', await p.locator('.row', { hasText: 'SPORRENCESON' }).textContent());
console.log('errors:', errs);
await b.close();
