// Regenerates nod-it-handoff/decks/ from the ROEL IT! source, verbatim.
//
//   CREW_CODE=<the deck code> node nod-it-handoff/scripts/build-handoff.mjs
//
// - Copies every src/decks/*.json byte-for-byte (including the encrypted
//   SPORRENCESON file, which NOD IT! ships as-is so the same code opens it).
// - Decrypts SPORRENCESON into decks/sporrenceson.json (plain reference copy).
// - Writes decks/MANIFEST.md with card counts and SHA-256 hashes.
// - Regenerates the SPORRENCESON card list inside NOD-IT-FULL-PROMPT.md.
// The code is read from the environment and never written anywhere.
import { createHash } from 'node:crypto';
import { copyFileSync, readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { open } from '../../src/vault-crypto.ts';

const ROOT = new URL('../../', import.meta.url).pathname;
const SRC = join(ROOT, 'src/decks');
const OUT = join(ROOT, 'nod-it-handoff/decks');
const PROMPT = join(ROOT, 'nod-it-handoff/NOD-IT-FULL-PROMPT.md');
const sha = (buf) => createHash('sha256').update(buf).digest('hex');

const code = process.env.CREW_CODE;
if (!code) throw new Error('Set CREW_CODE to decrypt SPORRENCESON');

const rows = [];
for (const f of readdirSync(SRC).filter((f) => f.endsWith('.json')).sort()) {
  const from = join(SRC, f);
  const outName = f === 'the-crew.locked.json' ? 'sporrenceson.locked.json' : f;
  copyFileSync(from, join(OUT, outName));
  const a = readFileSync(from);
  const b = readFileSync(join(OUT, outName));
  if (sha(a) !== sha(b)) throw new Error(`copy changed ${f}`);
  const d = JSON.parse(a.toString());
  const cards = d.cards?.length ?? d.count;
  const aliases = (d.cards ?? []).filter((c) => typeof c === 'object').length;
  rows.push({ file: outName, source: `src/decks/${f}`, id: d.id, name: d.name, color: d.color, icon: d.icon, cards, aliases, sha: sha(b), note: d.sealed ? 'encrypted (ship this one)' : '' });
}

// Plain SPORRENCESON reference copy.
const locked = JSON.parse(readFileSync(join(SRC, 'the-crew.locked.json'), 'utf8'));
const plain = await open(locked.sealed, code);
if (plain == null) throw new Error('Wrong CREW_CODE');
const { sealed, count, codeLength, ...meta } = locked;
const cards = JSON.parse(plain);
if (cards.length !== count) throw new Error(`decrypted ${cards.length} cards, expected ${count}`);
const plainJson = JSON.stringify({ ...meta, cards }, null, 2) + '\n';
writeFileSync(join(OUT, 'sporrenceson.json'), plainJson);
rows.push({ file: 'sporrenceson.json', source: 'decrypted from src/decks/the-crew.locked.json', id: meta.id, name: meta.name, color: meta.color, icon: meta.icon, cards: cards.length, aliases: cards.filter((c) => typeof c === 'object').length, sha: sha(Buffer.from(plainJson)), note: 'plain reference copy, do NOT bundle' });
// Same cards inside and out: hash of the decrypted card array vs this file's cards.
const cardsHash = sha(Buffer.from(JSON.stringify(cards)));

const md = [
  '# Deck manifest',
  '',
  'Generated by `scripts/build-handoff.mjs` from the ROEL IT! repo. Every file is a byte-for-byte copy of `src/decks/` except `sporrenceson.json`, which is the decrypted plain copy of the encrypted deck.',
  '',
  '| File | Deck name | id | Colour key | Icon | Cards | Cards with aliases | SHA-256 | Note |',
  '|---|---|---|---|---|---|---|---|---|',
  ...rows.map((r) => `| \`${r.file}\` | ${r.name} | \`${r.id}\` | \`${r.color}\` | \`${r.icon}\` | ${r.cards} | ${r.aliases} | \`${r.sha}\` | ${r.note} |`),
  '',
  `Total cards: ${rows.filter((r) => r.file !== 'sporrenceson.locked.json').reduce((a, r) => a + r.cards, 0)} (8 built-in decks + SPORRENCESON).`,
  '',
  `SPORRENCESON card-array hash (\`sha256(JSON.stringify(cards))\`, identical for the decrypted locked file and \`sporrenceson.json\`): \`${cardsHash}\``,
  '',
  'Check with: `node nod-it-handoff/scripts/check-handoff.mjs` (no code needed).',
  '',
].join('\n');
writeFileSync(join(OUT, 'MANIFEST.md'), md);

// SPORRENCESON list inside the prompt, generated from the JSON.
if (existsSync(PROMPT)) {
  const list = cards
    .map((c, i) => (typeof c === 'string' ? `${i + 1}. ${c}` : `${i + 1}. ${c.text}${c.aliases?.length ? ` (aliases: ${c.aliases.join(', ')})` : ''}`))
    .join('\n');
  const p = readFileSync(PROMPT, 'utf8');
  const re = /<!-- SPORRENCESON:START -->[\s\S]*<!-- SPORRENCESON:END -->/;
  if (!re.test(p)) throw new Error('prompt is missing the SPORRENCESON markers');
  writeFileSync(PROMPT, p.replace(re, `<!-- SPORRENCESON:START -->\n${list}\n<!-- SPORRENCESON:END -->`));
}
console.log(rows.map((r) => `${r.file.padEnd(28)} ${String(r.cards).padStart(3)} cards  ${r.sha.slice(0, 12)}`).join('\n'));
